steps:
# Install dependencies
- name: node:12
  entrypoint: npm
  args: ['install']
# Run build commands
- name: node:12
  entrypoint: npm
  args: ['run', 'build']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wired-axis-270905/myvuejs', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wired-axis-270905/myvuejs']

images:
- gcr.io/wired-axis-270905/myvuejs  
